# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3138a723564c6e43318453d5b0c4a69368ef903c635596d7407983bbe66d405d96046b40b0efee2232086906ef2705326350200e67ca448aee45c6830946ecd5

test:
  secret_key_base: 15675142ac29feb5411f966313a34ff9f9a664846ef6a52080a5c83f731e55fb52957183248c2dd675cd53230522c0dd4200850fe1c0c5210dd86a467dabd651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
